name: create pr laravel-9

on:
  push:
    branches: [ main ]

jobs:
  create-pr-laravel9:

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check if pr exists
        id: check-if-pr-exists
        run: |
          pr_title=${{ github.ref == 'main' }}
          base_branch=${{ github.ref == 'refs/heads/feature/laravel-9' }}
          echo "::set-output name=count::$(gh pr list -S ${pr_title}' in::title' -B $base_branch | wc -l)"
          echo "::set-output name=pr_title::$pr_title"
          echo "::set-output name=base_branch::$base_branch"

      - name: create laravel-9 pr
        if: ${{ steps.check-if-pr-exists.outputs.count == 0 }}
        uses: peter-evans/create-pull-request@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: inc package patch-${{ steps.branch-name.outputs.current_branch }} version
            signoff: false
            branch: ${{ steps.branch-name.outputs.base_branch }}
            delete-branch: true
            title: Pre Release Packages ( ${{ steps.branch-name.outputs.current_branch }} )
            body: Pre Release Packages for branch is ${{ steps.branch-name.outputs.current_branch }}
            labels: pre-release-packages
            draft: false
            base: ${{ steps.branch-name.outputs.current_branch }}
