name: create pr laravel-9

on:
  push:
    branches: [ main ]

jobs:
  create-pr-laravel9:

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: 'Asia/Tokyo'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: check if pr exists
        id: check-if-pr-exists
        run: |
          echo "::set-output name=count::$(gh pr list -S Laravel9' in::title' -B feature/laravel-9 | wc -l)"

      - name: create laravel-9 pr
        if: ${{ steps.check-if-pr-exists.outputs.count == 0 }}
        id: create-pr
        run: |
          gh pr create -B feature/laravel-9 -t "Patch Laravel9 $(date +'%Y-%m-%d-%H:%M:%S')" -b ""
