name: create pr laravel-9

on:
  push:
    branches: [ main ]

jobs:
  create-pr-laravel9:

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: 'Asia/Tokyo'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check if pr exists
        id: check-if-pr-exists
        run: |
          echo "count=$(gh pr list -S "Patch Laravel9"' in::title' -B feature/laravel-9 | wc -l) > $GITHUB_OUTPUT"
      - name: create laravel-9 pr
        if: ${{ steps.check-if-pr-exists.outputs.count == 0 }}
        id: create-pr
        run: |
          echo "pr_url=$(gh pr create -B feature/laravel-9 -t "Patch Laravel9" -b "") > $GITHUB_OUTPUT"
      - name: merge pr patch laravel9
        id: merge-pr
        run: |
          gh pr merge ${{steps.create-pr.outputs.pr_url}} --merge --admin
      - name: failure to log
        if: failure() && steps.merge-pr.outcome == 'failure'
        run: |
          echo "conflict laravel9 pr"
