name: create pr laravel-9

on:
  push:
    branches: [ main ]

jobs:
  create-pr-laravel9:

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TZ: 'Asia/Tokyo'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: create laravel-9 pr
        id: create-pr
        run: |
          gh pr create -B feature/laravel-9 -t "Patch laravel9 $(date +'%Y-%m-%d-%H:%M:%S')" -b ""
