name: workflow-dispatch

on:
  workflow_dispatch: 
    branches:
      - main
jobs:
    workflow-dispatch:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Hello World
            run: echo "Hello World"
